// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CryptogramGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("encoded")]
        public string Encoded { get; set; }

        [JsonProperty("original")]
        public string Original { get; set; }

        [JsonProperty("cipher")]
        public Cipher Cipher { get; set; }

        [JsonProperty("letterCount")]
        public long LetterCount { get; set; }

        [JsonProperty("wordCount")]
        public long WordCount { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }

        [JsonProperty("image")]
        public Image Image { get; set; }

        [JsonProperty("solutionImage")]
        public Image SolutionImage { get; set; }
    }

    public partial class Cipher
    {
        [JsonProperty("A")]
        public string A { get; set; }

        [JsonProperty("B")]
        public string B { get; set; }

        [JsonProperty("C")]
        public string C { get; set; }

        [JsonProperty("D")]
        public string D { get; set; }

        [JsonProperty("E")]
        public string E { get; set; }

        [JsonProperty("F")]
        public string F { get; set; }

        [JsonProperty("G")]
        public string G { get; set; }

        [JsonProperty("H")]
        public string H { get; set; }

        [JsonProperty("I")]
        public string I { get; set; }

        [JsonProperty("J")]
        public string J { get; set; }

        [JsonProperty("K")]
        public string K { get; set; }

        [JsonProperty("L")]
        public string L { get; set; }

        [JsonProperty("M")]
        public string M { get; set; }

        [JsonProperty("N")]
        public string N { get; set; }

        [JsonProperty("O")]
        public string O { get; set; }

        [JsonProperty("P")]
        public string P { get; set; }

        [JsonProperty("Q")]
        public string Q { get; set; }

        [JsonProperty("R")]
        public string R { get; set; }

        [JsonProperty("S")]
        public string S { get; set; }

        [JsonProperty("T")]
        public string T { get; set; }

        [JsonProperty("U")]
        public string U { get; set; }

        [JsonProperty("V")]
        public string V { get; set; }

        [JsonProperty("W")]
        public string W { get; set; }

        [JsonProperty("X")]
        public string X { get; set; }

        [JsonProperty("Y")]
        public string Y { get; set; }

        [JsonProperty("Z")]
        public string Z { get; set; }
    }

    public partial class Image
    {
        [JsonProperty("imageName")]
        public string ImageName { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("downloadURL")]
        public Uri DownloadUrl { get; set; }

        [JsonProperty("expires")]
        public long Expires { get; set; }
    }
}
